before_install:
   - sudo apt-get install ant-optional
     
language: java

jdk:
   - oraclejdk9

script: 
   - ant main
   - mvn -f testpom.xml -Pjacoco coveralls:report

after_success: 

notifications:
  email:
    recipients:
      - davide.basile@isti.cnr.it