before_install:
   - sudo apt-get install ant-optional
     
language: java

jdk:
   - oraclejdk9

script: ant main

after_success: "sbt coveralls"

notifications:
  email:
    recipients:
      - davide.basile@isti.cnr.it