before_install:
   - sudo apt-get install ant-optional
   
language: java
script: ant main
jdk:      oraclejdk9

after_success: "sbt coveralls"

notifications:
  email:
    recipients:
      - davide.basile@isti.cnr.it