#https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
#https://hyp0th3rmi4.medium.com/configuring-coveralls-io-reports-for-maven-builds-with-github-actions-393b11fa3402

name: GitHub CI

on: [push]

jobs:
  buildtest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: 📦 Build with Maven 
        run: mvn -B jacoco:prepare-agent verify jacoco:report
        
      - name: 🚀 Coveralls Coverage Report Submission
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: mvn coveralls:report --define repoToken=${{ secrets.COVERALLS_REPO_TOKEN }}
        
      - name: 🐛 Analyze with SonarCloud and SpotBugs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=ContractAutomataProject_ContractAutomataLib spotbugs:check

      - name: 👓 Mutation Testing with Pit
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: mvn -DwithHistory test-compile org.pitest:pitest-maven:mutationCoverage
        
      - name: 🚀 Upload Mutation Test Report
        run: ./.github/upload-mutation-report.sh
        env:
          API_KEY: ${{ secrets.STRYKER_DASHBOARD_TOKEN }}
